version: 2
jobs:
  test:
    docker:
      - image: rust
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install virtualenv libsystemd-dev libdbus-glib-1-dev libgirepository1.0-dev libdbus-1-dev dbus netcat-openbsd
      - run: make pacparser
      - run: make -C parparser/src install
      - run: make check
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
