version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - run: sudo apt-get install libsystemd-dev libdbus-glib-1-dev libgirepository1.0-dev dbus
      - run: make check
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
